### PR TITLE
SPFBO 1, 2 and 3

### PR DESCRIPTION
**Pull request by beanz**
Wow. These were much harder as lots are unavailable or re-issued with slightly different names, etc.  Even using the wayback machine for blogs that don't exist any more, I could only find semi-finalist details for some blogs.

### CODE REVIEW

**Comment by zackargyle** [comment]
Looks great! Amazing contributions, Mark!

**Comment by zackargyle** [comment]
@beanz, I removed the next/image optimization (too expensive) and that looks like it broke your s3 links which are http. Any way we can make those https?

**Comment by beanz** [comment]
Not easily since s3 only supports http. I'll give it some thought later.

**Comment by beanz** [comment]
Taking a quick look, I can use AWS cloudfront to front the S3 bucket via HTTPS. I'll make a PR shortly with the changes.

**Pull request merged**
